version: "3.1"
services:
  ### mysql ###################################################
  mysql:
    image: mysql
    container_name: ${DOCKER_PROJECT_NAME}-mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${DOCKER_MYSQL_PORT}:${DB_PORT}
