FROM node:18

WORKDIR /app

# Копіюємо package.json та package-lock.json
COPY package*.json ./

# Встановлюємо залежності
RUN npm install

# Копіюємо всі файли проекту
COPY . .

# Відкриваємо порт для розробки
EXPOSE 5173

# Запускаємо dev сервер з hot reload
CMD ["npm", "run", "dev"]